import mysql from "mysql2/promise";
import { randomUUID } from "crypto";

const db = await mysql.createConnection(process.env.DATABASE_URL);
const now = Date.now();

const applicants = [
  {
    status: "approved",
    adminNotes: "Strong candidate — consistent and knowledgeable",
    tracks: JSON.stringify(["community", "content"]),
    contributionIntent: "community",
    testScore: 9,
    communities: "Singapore Crypto Community, DeFi Asia",
    twitterHandle: "@alexchen_crypto",
    telegramHandle: "@alexchen",
    githubHandle: "@alexchen",
    otherLinks: "",
    hasCommunityExperience: "yes",
    communityLinks: JSON.stringify([{url:"https://t.me/sgcrypto", description:"Singapore Crypto Community - 3000 members"}]),
    protocolDescription: "This protocol is building next-generation infrastructure for cross-border value transfer.",
    communityBenefit: "I run a crypto community of 3,000 members and have been explaining DeFi infrastructure for 2 years.",
    firstThirtyDays: "Week 1: Deep-dive thread on the protocol's market maker model. Week 2: Video explainer on stablecoin settlement. Week 3: Community AMA. Week 4: Recap post.",
    email: "alex.chen@demo.com",
    isEvangelist: 0,
    lastStep: "submitted",
    level: 2,
    evangelistCandidate: 1,
    xContentScore: 8,
    xEngagementScore: 7,
    xConsistencyScore: 9,
    communityContribScore: 8,
    tgActivityScore: 7,
    adminOverrideScore: 0,
    totalScore: 87,
    scoreTrend: 1,
    weeklyScores: JSON.stringify([65, 70, 78, 87]),
    badges: JSON.stringify(["knowledgeable","consistent","creator","amplifier","community_builder"]),
    avatarUrl: null,
    displayHandle: "@alexchen_crypto",
    createdAt: now - 7 * 24 * 60 * 60 * 1000,
    updatedAt: now,
  },
  {
    status: "approved",
    adminNotes: "Perfect score — exceptional content creator",
    tracks: JSON.stringify(["content"]),
    contributionIntent: "content",
    testScore: 10,
    communities: "Filipino Crypto Creators, DeFi Philippines",
    twitterHandle: "@mariasantos_fx",
    telegramHandle: "@mariasantos",
    githubHandle: "",
    otherLinks: "",
    hasCommunityExperience: "yes",
    communityLinks: JSON.stringify([{url:"https://twitter.com/mariasantos_fx", description:"Main X account - 15k followers"}]),
    protocolDescription: "This protocol solves the last-mile problem in cross-border transfers through decentralized infrastructure.",
    communityBenefit: "Content creator with 15k followers on X focused on DeFi education.",
    firstThirtyDays: "Launch a 10-part thread series breaking down the protocol's architecture. Produce 2 short-form videos.",
    email: "maria.santos@demo.com",
    isEvangelist: 0,
    lastStep: "submitted",
    level: 2,
    evangelistCandidate: 1,
    xContentScore: 9,
    xEngagementScore: 8,
    xConsistencyScore: 7,
    communityContribScore: 6,
    tgActivityScore: 5,
    adminOverrideScore: 0,
    totalScore: 82,
    scoreTrend: 1,
    weeklyScores: JSON.stringify([55, 65, 74, 82]),
    badges: JSON.stringify(["perfect_score","articulate","creator","high_reach"]),
    avatarUrl: null,
    displayHandle: "@mariasantos_fx",
    createdAt: now - 6 * 24 * 60 * 60 * 1000,
    updatedAt: now,
  },
  {
    status: "approved",
    adminNotes: "Strong community builder — Lagos Web3 lead",
    tracks: JSON.stringify(["community", "developer"]),
    contributionIntent: "community",
    testScore: 8,
    communities: "Web3 Lagos, Nigeria DeFi",
    twitterHandle: "@jamesokafor_web3",
    telegramHandle: "@jamesokafor",
    githubHandle: "@jamesokafor",
    otherLinks: "",
    hasCommunityExperience: "yes",
    communityLinks: JSON.stringify([{url:"https://t.me/web3lagos", description:"Web3 Lagos - 2000 members"}]),
    protocolDescription: "This protocol enables atomic swaps between stablecoins — removing the need for traditional intermediaries.",
    communityBenefit: "Developer and community lead for Web3 Lagos, 2000+ members. Built 3 DeFi integrations.",
    firstThirtyDays: "Host a Lagos Web3 meetup focused on the protocol. Build a simple demo integration. Post weekly updates.",
    email: "james.okafor@demo.com",
    isEvangelist: 0,
    lastStep: "submitted",
    level: 1,
    evangelistCandidate: 1,
    xContentScore: 7,
    xEngagementScore: 6,
    xConsistencyScore: 8,
    communityContribScore: 9,
    tgActivityScore: 8,
    adminOverrideScore: 0,
    totalScore: 74,
    scoreTrend: 1,
    weeklyScores: JSON.stringify([50, 58, 66, 74]),
    badges: JSON.stringify(["knowledgeable","consistent","community_builder","amplifier"]),
    avatarUrl: null,
    displayHandle: "@jamesokafor_web3",
    createdAt: now - 5 * 24 * 60 * 60 * 1000,
    updatedAt: now,
  },
  {
    status: "pending",
    adminNotes: "",
    tracks: JSON.stringify(["content"]),
    contributionIntent: "content",
    testScore: 7,
    communities: "DeFi Germany, European Crypto Writers",
    twitterHandle: "@sofiamueller_defi",
    telegramHandle: "@sofiamueller",
    githubHandle: "",
    otherLinks: "",
    hasCommunityExperience: "no",
    communityLinks: JSON.stringify([]),
    protocolDescription: "This protocol enables on-chain settlement through a decentralized market maker model.",
    communityBenefit: "DeFi researcher and writer. Published in major crypto media.",
    firstThirtyDays: "Write 3 long-form articles about the protocol. Translate content to German for European audience.",
    email: "sofia.mueller@demo.com",
    isEvangelist: 0,
    lastStep: "submitted",
    level: 1,
    evangelistCandidate: 0,
    xContentScore: 6,
    xEngagementScore: 5,
    xConsistencyScore: 6,
    communityContribScore: 5,
    tgActivityScore: 4,
    adminOverrideScore: 0,
    totalScore: 61,
    scoreTrend: 0,
    weeklyScores: JSON.stringify([45, 52, 58, 61]),
    badges: JSON.stringify(["knowledgeable","articulate"]),
    avatarUrl: null,
    displayHandle: "@sofiamueller_defi",
    createdAt: now - 4 * 24 * 60 * 60 * 1000,
    updatedAt: now,
  },
  {
    status: "pending",
    adminNotes: "",
    tracks: JSON.stringify(["developer"]),
    contributionIntent: "developer",
    testScore: 9,
    communities: "Japan DeFi Builders, Solidity Japan",
    twitterHandle: "@kaitanaka_demo",
    telegramHandle: "@kaitanaka",
    githubHandle: "@kaitanaka",
    otherLinks: "",
    hasCommunityExperience: "yes",
    communityLinks: JSON.stringify([{url:"https://github.com/kaitanaka", description:"GitHub - 500+ followers, active DeFi contributor"}]),
    protocolDescription: "This protocol is building the settlement layer for the on-chain economy — enabling real-time swaps at institutional scale.",
    communityBenefit: "Solidity developer with 5 years experience. Contributor to 3 open-source DeFi protocols.",
    firstThirtyDays: "Build an SDK wrapper in TypeScript. Document the integration process. Post weekly dev updates.",
    email: "kai.tanaka@example.com",
    isEvangelist: 0,
    lastStep: "submitted",
    level: 1,
    evangelistCandidate: 0,
    xContentScore: 5,
    xEngagementScore: 5,
    xConsistencyScore: 7,
    communityContribScore: 6,
    tgActivityScore: 7,
    adminOverrideScore: 0,
    totalScore: 68,
    scoreTrend: 0,
    weeklyScores: JSON.stringify([48, 55, 62, 68]),
    badges: JSON.stringify(["knowledgeable","consistent","network_embedded"]),
    avatarUrl: null,
    displayHandle: "@kaitanaka_demo",
    createdAt: now - 3 * 24 * 60 * 60 * 1000,
    updatedAt: now,
  },
  {
    status: "pending",
    adminNotes: "",
    tracks: JSON.stringify(["community"]),
    contributionIntent: "community",
    testScore: 6,
    communities: "India DeFi",
    twitterHandle: "@priyasharma_web3",
    telegramHandle: "@priyasharma",
    githubHandle: "",
    otherLinks: "",
    hasCommunityExperience: "yes",
    communityLinks: JSON.stringify([{url:"https://t.me/indiadefi", description:"India DeFi community"}]),
    protocolDescription: "This protocol enables on-chain cross-border settlement.",
    communityBenefit: "Community manager for a DeFi project.",
    firstThirtyDays: "Post about the protocol on X and engage with the community.",
    email: "priya.sharma@demo.com",
    isEvangelist: 0,
    lastStep: "submitted",
    level: 0,
    evangelistCandidate: 0,
    xContentScore: 3,
    xEngagementScore: 3,
    xConsistencyScore: 4,
    communityContribScore: 5,
    tgActivityScore: 4,
    adminOverrideScore: 0,
    totalScore: 44,
    scoreTrend: -1,
    weeklyScores: JSON.stringify([40, 48, 50, 44]),
    badges: JSON.stringify(["community_builder"]),
    avatarUrl: null,
    displayHandle: "@priyasharma_web3",
    createdAt: now - 2 * 24 * 60 * 60 * 1000,
    updatedAt: now,
  },
];

for (const a of applicants) {
  const [result] = await db.execute(
    `INSERT INTO ambassador_applications (
      status, adminNotes, tracks, contributionIntent, testScore, communities,
      twitterHandle, telegramHandle, githubHandle, otherLinks,
      hasCommunityExperience, communityLinks, protocolDescription, communityBenefit,
      firstThirtyDays, email, isEvangelist, lastStep, level, evangelistCandidate,
      xContentScore, xEngagementScore, xConsistencyScore, communityContribScore,
      tgActivityScore, adminOverrideScore, totalScore, scoreTrend, weeklyScores,
      badges, avatarUrl, displayHandle, createdAt, updatedAt
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
    [
      a.status, a.adminNotes, a.tracks, a.contributionIntent, a.testScore,
      a.communities, a.twitterHandle, a.telegramHandle, a.githubHandle,
      a.otherLinks, a.hasCommunityExperience, a.communityLinks,
      a.protocolDescription, a.communityBenefit, a.firstThirtyDays, a.email,
      a.isEvangelist, a.lastStep, a.level, a.evangelistCandidate,
      a.xContentScore, a.xEngagementScore, a.xConsistencyScore,
      a.communityContribScore, a.tgActivityScore, a.adminOverrideScore,
      a.totalScore, a.scoreTrend, a.weeklyScores, a.badges,
      a.avatarUrl, a.displayHandle, a.createdAt, a.updatedAt,
    ]
  );
  const insertId = result.insertId;
  console.log(`Inserted: ${a.twitterHandle} (id: ${insertId})`);

  // Add journal entries for top applicant
  if (a.email === "alex.chen@demo.com") {
    await db.execute(
      `INSERT INTO journal_entries (applicationId, type, title, content, createdAt, updatedAt)
       VALUES (?, ?, ?, ?, ?, ?)`,
      [
        insertId, "plan",
        "Week 1 Plan — Launch Thread Series",
        "Goal: Publish a 10-tweet thread breaking down the protocol's market maker model. I need to study the whitepaper more carefully and find 3 real-world examples of cross-border FX pain points that This protocol solves. Target: 500 impressions minimum.",
        now - 5 * 24 * 60 * 60 * 1000,
        now - 5 * 24 * 60 * 60 * 1000,
      ]
    );
    await db.execute(
      `INSERT INTO journal_entries (applicationId, type, title, content, createdAt, updatedAt)
       VALUES (?, ?, ?, ?, ?, ?)`,
      [
        insertId, "reflection",
        "Week 1 Reflection — What worked, what didn't",
        "The thread got 800 impressions which exceeded my goal. The best-performing tweet was the one comparing the protocol to SWIFT but on-chain. Next week I'll lean into more analogies. Need to be more consistent with reply engagement — I only replied to 3 comments when I should have replied to all of them.",
        now - 2 * 24 * 60 * 60 * 1000,
        now - 2 * 24 * 60 * 60 * 1000,
      ]
    );
    console.log(`  → Added 2 journal entries for ${a.twitterHandle}`);
  }
}

await db.end();
console.log("\nSeed complete — 6 demo applicants inserted.");
